export const theme = {
	primary: 'green',
	dim: 'gray',
	warn: 'yellow',
	error: 'red',
	accent: 'cyan',
	bright: 'white',
	prompt: '>',
	cursor: '█',
	filled: '█',
	empty: '░',
	borderH: '═',
	borderV: '║',
	borderTL: '╔',
	borderTR: '╗',
	borderBL: '╚',
	borderBR: '╝',
	borderL: '╠',
	borderR: '╣',
} as const;
